name: deploy-to-github

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout on release branch
      uses: actions/checkout@master
    - name: Setup node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn
    - run: yarn gulp deploy
