name: deploy-to-github

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout on master branch
      uses: actions/checkout@master
    - name: Setup node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn
    - run: yarn gulp
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        repo: Quelu/quelu.github.io
        target_branch: master
        build_dir: dist
        committer_name: Quelu
        committer_email: ${{ secrets.USER_EMAIL }}
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
